@baseUrl = https://localhost:7236/api/v1/companies

@token = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMyZjVmNzBiLTg3MzQtNGI5MC05NTZmLWZmZmRiNjcxODViYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImNvbXBhbnkxQGV4YW1wbGUuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ29tcGFueSIsImV4cCI6MTc3MzcyODY5MSwiaXNzIjoibG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.Gd2kiu6phxWqkWcKYmLadIsT0HFh6f03VDgiVgyCBtM

@refreshToken = 7CucaXCHCxaZZ7symWCu6mR1lWrDlqWrgHomvFjN06g=

###
GET {{baseUrl}}/me
Authorization: Bearer {{token}}
