@baseUrl = https://localhost:7236/api/job-seekers

@id = 7ff07b79-3124-4ad9-8187-f1d6a17c0bb5

###
POST {{baseUrl}}
Content-Type: application/json

{
  "email": "yusfgus@example.com",
  "password": "StrongPassword123!",
  "profilePictureUrl": "https://example.com/profile.jpg",
  "summary": "A brief summary of the user profile.",
  "firstName": "Yousef",
  "lastName": "Sayed",
  "mobileNumber": "+1234567890",
  "birthDate": "1990-01-01",
  "country": "Egypt",
  "gender": "Male",
  "nationality": "Egyptian"
}

# {
#   "user": {
#     "email": "johndoe@example.com",
#     "password": "StrongPassword123!",
#     "profilePictureUrl": "https://example.com/profile.jpg",
#     "role": "JobSeeker",
#     "summary": "A brief summary of the user profile."
#   },
#   "name": {
#     "firstName": "John",
#     "middleName": "William",
#     "lastName": "Doe"
#   },
#   "mobileNumber": "+1234567890",
#   "birthDate": "1990-01-01",
#   "address": {
#     "country": "United States",
#     "city": "New York",
#     "area": "Manhattan"
#   },
#   "gender": "Male",
#   "nationality": "American",
#   "militaryStatus": "Exempted",
#   "maritalStatus": "Single"
# }
